### ISSUE TITLE
autoconf, make, etc

### ISSUE THREAD

**Issue by ktruckenmiller** [mikebrady/shairport-sync-metadata-reader#1]
Hey Mike, 

Awesome idea by the way. Just getting this setup on my raspberry pi.

Do you have install instructions?  Just trying to get it up and running and I'm running into issues, it says:

$ autoconf
configure.ac:6 error: possibly undefined macro: AM_INIT_AUTOMAKE

**Comment by mikebrady** [comment]
Hi Kevin. Try `autoreconf -i -f` followed by `./configure`. I should write this down...

**Comment by ktruckenmiller** [comment]
I'll get back to it next week. Great job on all this stuff! Really fun
