### ISSUE TITLE
Decoding

### ISSUE THREAD

**Issue by dnnspaul** [mikebrady/shairport-sync-metadata-reader#10]
Hi!

> The type and code are 4-character codes each encoded as 8 hexadecimal digits -- they can be read into C as 32-bit integers.

I am not able to reproduce this in nodejs / javascript. Can you help? I'm not down with converting of formats.

**Comment by dnnspaul** [comment]
So far:

`var fs = require('fs');
var readableStream = fs.createReadStream('/tmp/shairport-sync-metadata');
var parseString = require('xml2js').parseString;

var item = "";

readableStream.on('data', function(chunk) {
    try {
        var data = chunk.toString("utf-8").trim().replace(/\r?\n|\r/g, '');

```
    item += data;

    if(data.indexOf("</item>") > -1) {
        parseString(item, function (err, result) {
            //result["item"]["type"] = result["item"]["type"].toString(16);
            console.log(result);
            item = "";
        });
    }
}
catch (e) {
    console.log(e);
    item = "";
}
```

});

readableStream.on('end', function() {
    console.log("END: " + data);
});`

The problem is in line 15. Don't know how to convert it, to get the type and code.

**Comment by mikebrady** [comment]
I'm glad you sorted it how. How did you fix it?
