### ISSUE TITLE
Image format of album art

### ISSUE THREAD

**Issue by ChrisBGriffith** [mikebrady/shairport-sync-metadata-reader#14]
I was successfully able to add a couple of lines around 178 that dump the contents of b64buf to a file. I tried both JPG and PNG files and neither resulted in a proper file, though the file size was correct. Does the image need to be further processed and how can I tell which format the image is?

**Comment by mikebrady** [comment]
Thanks for the post. The first few bytes of the data will tell you what kind of image you have – Google is your friend here. You can use the information to add the appropriate extension to the file.

**Comment by ChrisBGriffith** [comment]
Thanks, I was able to get the image displayed in a Processing app by modifying the reader to dump the image data to a file each time a new song comes in.

**Comment by lordbarba** [comment]
Hi Chris, 
may you share your solution, please? I'm trying to do the same with no result.

Thanks
Leo

**Comment by lordbarba** [comment]
Solved!.

**Comment by AlexanderTheDecent** [comment]
can you share the code? I would like to be able to get the picture

**Comment by AlexanderTheDecent** [comment]
would you mind sharing that code? I'm trying to figure out how to get the album art to a state where some other code can manipulate it

**Comment by Clovel** [comment]
I would also like to have an example code for this. 

Thanks, 
Clovel
