### ISSUE TITLE
Airplay metadata from iOS 11 not showing album or track names 

### ISSUE THREAD

**Issue by leedowthwaite** [mikebrady/shairport-sync-metadata-reader#16]
Hi, 

First, thanks for all your hard work on these projects - great stuff!

I just got shairport-sync up and running on Raspbian (Pi model 3 A+) and configured it to pipe metadata. It plays fine from Airplay on iOS 11. But shairport-sync-metadata-reader is just displaying output like this:-

```
"ssnc" "flsr": "1776932189".
"ssnc" "pfls": "".
"ssnc" "pffr": "".
"ssnc" "prsm": "".
"ssnc" "flsr": "1777075073".
"ssnc" "pfls": "".
"ssnc" "pffr": "".
"ssnc" "flsr": "1777077718".
"ssnc" "pfls": "".
"ssnc" "pffr": "".
"ssnc" "prsm": "".
"ssnc" "flsr": "1777165037".
"ssnc" "pfls": "".
```
My config file has a metadata section like this:-
```
// How to deal with metadata, including artwork
metadata =
{
	enabled = "yes"; // set this to yes to get Shairport Sync to solicit metadata from the source and to pass it on via a pipe
	include_cover_art = "no"; // set to "yes" to get Shairport Sync to solicit cover art from the source and pass it via the pipe. You must also set "enabled" to "yes".
	pipe_name = "/tmp/shairport-sync-metadata";
	pipe_timeout = 5000; // wait for this number of milliseconds for a blocked pipe to unblock before giving up
//	socket_address = "226.0.0.1"; // if set to a host name or IP address, UDP packets containing metadata will be sent to this address. May be a multicast address. "socket-port" must be non-zero and "enabled" must be set to yes"
//	socket_port = 5555; // if socket_address is set, the port to send UDP packets to
//	socket_msglength = 65000; // the maximum packet size for any UDP metadata. This will be clipped to be between 500 or 65000. The default is 500.
};
```

I'd expected to see track names and such. Am I doing something wrong?

**Comment by leedowthwaite** [comment]
No worries, I fixed it. Just uncommented everything inside the `meta` key in the config file and restarted the service - now I have artists/album/track names.

**Comment by mikebrady** [comment]
Great — that’s what I was going to suggest... The socket stuff isn't necessary for this use, but `enabled` must be `"yes"` to enable Shairport Sync to ask the source for the metadata. Sometimes the cover art is so bulky that it can bog down the transmission, so you can leave it off if you have no use for it.
