### ISSUE TITLE
Incoherent values for input length & output length in example. 

### ISSUE THREAD

**Issue by Clovel** [mikebrady/shairport-sync-metadata-reader#17]
Hi, 

I have noticed that the values for `inputlength` (l. 171) & `outputlength` (l. 174) are incoherent. We have : 
 * `int inputlength = 32678`
 * `int outputlength = 32768`

Which is the correct value ? Is this difference voluntary. I can't quite figure it out. 

Anyway, the way I see it is that this value will be overwritten for `inputlength`. 

Thanks, 
Clovel

**Comment by mikebrady** [comment]
Thanks for the post. It's a mhistake – I was thinking of 32768. You are right that is can be overwritten – it will be replaced by the true size of the incoming picture data if less than 32768 bytes remain. Typically, though, pictures are larger, so this code has the effect of breaking the job of decoding an incoming picture into chunks that won't exceed 32768 bytes.

I've fixed the error. Thanks again.

**Comment by Clovel** [comment]
No worries. 

Btw, you answer my follow-up questions on image decoding. 

Thanks for the good work. 
Clovel
