### ISSUE TITLE
Incomplete image on pipe read

### ISSUE THREAD

**Issue by Clovel** [mikebrady/shairport-sync-metadata-reader#18]
Hi ! 

I am having issues with my own implementation of the metadata reader. When reading the output pipe in `/tmp/shairport-sync-metadata`, I get incomplete image data. If I save the data, the file is either unreadable (and a `std::cout <<` dump of the data only shows a newline) or the file is incomplete (viewable, but only the top of the file is valid, the rest is greyed out). 

My implementation is a messy C++ reinterpretation of your example. You can find the code here to reproduce if you want : https://github.com/Clovel/shairport-metadata-reader/issues/5, **dev** branch. 

It looks like the data sent is incomplete anyways. When I `cat` the pipe, copy and decode the image data, and dump it into a file, the file is readable but incomplete. Is it something I have to tweak on the `shairport-sync` side ? 

Thanks, 
Clovel

PS : Obviously, the code on my repo is WIP. And as all WIP code, ugly.

**Comment by mikebrady** [comment]
Taking a quick look at your code, it looks like it works on the basis that the picture data is in a single (long!) base64-encoded segment, but actually the picture data is sent as a sequence of length-limited base64-encoded segments, each followed by an end-of-line. Your code should read segments until enough data has been read.

**Comment by Clovel** [comment]
Ok, I will update the way I save the picture. 

Thanks for helping,
Clovel
