### ISSUE TITLE
Where's the picture?

### ISSUE THREAD

**Issue by mazeto** [mikebrady/shairport-sync-metadata-reader#22]
Hi.

The output says picture received. It even prints the picture size, but where does it go?
If you could add an option to output the picture as it is, base64, to a file, that would be awesome.

I would like use it the album picture to display a notification on my system with `notify-send`.

Thanks in advance.

**Comment by mikebrady** [comment]
Thanks for the post, and apologies for the long delay in replying. As it stands, the program reads and discards the actual picture information.

The thing is, the metadata reader is meant as a demonstrator only, and adding code to handle pictures would make it a lot longer. So, if you want to handle pictures, you'll have to write the code yourself.

Maybe some other developers have already done so (?).
