### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by luckydonald** [mikebrady/shairport-sync-metadata-reader#4]
[The INSTALL file (currently commit 4b69587f4)](https://github.com/mikebrady/shairport-sync-metadata-reader/blob/c4b69587f44a424a560bfccfbb8968e5ee144943/INSTALL#L15) states

``` shell
./configure; make; make install
```

But I get the error

``` shell
luckydonald@cubieNAS:~/tools/shairport-sync-metadata-reader$ ./configure
-bash: ./configure: No such file or directory
```

**Comment by luckydonald** [comment]
Okey, found https://github.com/mikebrady/shairport-sync-metadata-reader/issues/1#issuecomment-126825072 , telling me to use `autoreconf -i -f` before there is a `./configure` script.

**Comment by mikebrady** [comment]
Hi there. I need to update the install file – it's a default file. Please read the README.md file for full directions.

**Comment by mikebrady** [comment]
Fixed, I think.

**Comment by luckydonald** [comment]
I would consider writing that also into the README, as `autoreconf -i -f ; ./configure ; make ; sudo make install` is rather short.
Either way, thank you.

**Comment by mikebrady** [comment]
Thanks – I did that.
