### ISSUE TITLE
Problems about running shairport-sync-metadata-reader

### ISSUE THREAD

**Issue by xyorever** [mikebrady/shairport-sync-metadata-reader#7]
Hello Mike,

I have trouble running metadata-reader. I followed the instructions to install metadata-reader, and I did install metadata-reader on my laptop. 
`xyorever@xyorever:~/Downloads/shairport-sync-metadata-reader-master$ shairport-sync`
`shairport-sync                  shairport-sync-metadata-reader
`

However, the problem is that as long as I run it, it stops responding, even if I am running  help table. 
Here is the installing process, I don't know where it goes wrong.

`xyorever@xyorever:~/Downloads/shairport-sync-metadata-reader-master$ make`
`make  all-am`
`make[1]: Entering directory '/home/xyorever/Downloads/shairport-sync-metadata-reader-master'`
`gcc -DHAVE_CONFIG_H -I.    -Wno-multichar -g -O2 -MT shairport-sync-metadata-reader.o -MD -MP -MF .deps/shairport-sync-metadata-reader.Tpo -c -o shairport-sync-metadata-reader.o shairport-sync-metadata-reader.c`
`shairport-sync-metadata-reader.c: In function ‘main’:`
`shairport-sync-metadata-reader.c:248:38: warning: implicit declaration of function ‘htonl’ [-Wimplicit-function-declaration]`
 `*(uint32_t*)typestring = htonl(type);`
                       `^`
`mv -f .deps/shairport-sync-metadata-reader.Tpo .deps/shairport-sync-metadata-reader.Po`
`gcc -Wno-multichar -g -O2   -o shairport-sync-metadata-reader shairport-sync-metadata-reader.o`
`make[1]: Leaving directory '/home/xyorever/Downloads/shairport-sync-metadata-reader-master'`
`xyorever@xyorever:~/Downloads/shairport-sync-metadata-reader-master$ sudo make install`
`make[1]: Entering directory '/home/xyorever/Downloads/shairport-sync-metadata-reader-master'`
`/bin/mkdir -p '/usr/local/bin'`
`/usr/bin/install -c shairport-sync-metadata-reader '/usr/local/bin'`
`make[1]: Nothing to be done for 'install-data-am'.`
`make[1]: Leaving directory '/home/xyorever/Downloads/shairport-sync-metadata-reader-master'
`

 Could you please help me to fix this?

Thank you!

**Comment by mikebrady** [comment]
Hi there. Thanks for the post. Did you do a `./configure` on it first?

Also, I don't understand the line `zxyorever@xyorever:~/Downloads/shairport-sync-metadata-reader-master$ shairport-sync
shairport-sync shairport-sync-metadata-reader`. What is that meant to be?

**Comment by xyorever** [comment]
Thanks for the quick response.

I did do the `./configure` first. For the line `xyorever@xyorever:~/Downloads/shairport-sync-metadata-reader-master$ shairport-sync
shairport-sync shairport-sync-metadata-reader`  it is the result I pressed tab twice. I am just showing that the metadata-reader is installed on my laptop.

**Comment by mikebrady** [comment]
Okay, I get that now thanks. So, if you've followed the instructions:

```
$autoreconf -i -f
$./configure
$make
$sudo make install
```

then the above message is just a warning – the program has been compiled and installed. To check, do

```
$which shairport-sync-metadata-reader
```

you should get back:

```
/usr/local/bin/shairport-sync-metadata-reader
```

That confirms that it's installed.

**Comment by xyorever** [comment]
`xyorever@xyorever:~/Downloads/shairport-sync-metadata-reader-master$ which shairport-sync-metadata-reader
/usr/local/bin/shairport-sync-metadata-reader`

I believe it's indeed installed on my laptop, but the only problem is that it's unable to run it. 

`xyorever@xyorever:/$ shairport-sync-metadata-reader < /tmp/shairport-sync-metadata`

This is the command for running it, and just after I entered the command, it stopped responding. I don't know where it went wrong. Because I couldn't get any information from running the command, I assume that something went wrong during the installing process.

**Comment by xyorever** [comment]
In addition, there is no responding when I an running `shairport-sync-metadata-reader --help` or `-h`, even `-abcd`, and there is no configure file under `/etc` directory either.

**Comment by mikebrady** [comment]
Thanks for your posts. The program is very simple – it listens to the pipe, parses it and prints the parsed result out. A quick glance at the code will reveal that it provides no help strings and doesn't use configuration files. When you start it up, it should do nothing until some metadata is sent through the pipe, and then it should output the parsed results. If it appears to be doing nothing, then maybe there is no metadata going into the pipe. The metadata comes from shairport sync running on the same machine, compiled with metadata support and running with metadata enabled. In addition, it must have permission to write to the metadata pipe. So, have you compiled and set up shairport sync like that? Is metadata flowing into the pipe when it should?

**Comment by xyorever** [comment]
It worked after I changed the permissions of `/tmp/shairport-metadata`. Thanks a lot. But I didn't find the `acre` and `daid` tokens in metadata reader, do you know how to enable those tokens?

**Comment by xyorever** [comment]
Okay, never mind, I found the two tokens, they are at the very beginning of the metadata. Thanks for your shairport-sync and metadata-reader, thanks for your quick response, thanks a lot.

**Comment by mikebrady** [comment]
That's great!
