### ISSUE TITLE
Request per TCP

### ISSUE THREAD

**Issue by thejacko12354** [mikebrady/shairport-sync-metadata-reader#8]
Hey Mike,
I'd like to adapt your little tool, so that I can pull informations over TCP for my instance of Home Automation.

Maybe you could give me some advise how to do it efficiently, because I've never written anything in C.

Greets
Jacko

**Comment by mikebrady** [comment]
Hi Jacko. I'm afraid it would be beyond my competence to teach you how to use C. There are lots of guides out there, and I also find Beej's Guide to Networking really useful.

The tool itself is meant to act as a guide – it's a simple enough program that reads the pipe from the standard input.

All the best
Mike

**Comment by thejacko12354** [comment]
Well thanks Mike for the answer.
I think I try to understand the encoding of the pipe and write a tool myself in python.

Greets Jacko

**Comment by mikebrady** [comment]
That sound good. It may be that some other people have used Python too.
