### ISSUE TITLE
User's IP Address

### ISSUE THREAD

**Issue by alex-osman** [mikebrady/shairport-sync-metadata-reader#9]
I was wondering if there is a way to find the IP address of the user who is streaming the music at the given time.

**Comment by mikebrady** [comment]
Hi there, and thanks for the post. The IP number is known to Shairport Sync when streaming is occurring, so it would be possible to send it as a metadata item. I'll put it on the list of things to do. BTW, it could be IPv4 or IPv6.

**Comment by alex-osman** [comment]
Yes, I've seen it on the verbose output of Shairport Sync, was wondering if it was something it already logged to metadata or not.  But thanks!

**Comment by roblan** [comment]
You can find it using mDNS while searching for dacp tcp named iTunes_Ctrl_(DACP_ID) (which is already in the metadata). It's a little complicated but doable :)

There is a little about it here
https://www.sugrsugr.com/index.php/airplay-prev-next/

**Comment by mikebrady** [comment]
Thanks for the suggestion. I've added a metadata item `clip` to the latest development version. I'd be obliged if you tried it out.

**Comment by mikebrady** [comment]
There's been a further update to this in the latest versions of Shairport Sync.
